/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as RegistrationSubmittedRouteImport } from './routes/registration-submitted'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesNewRouteImport } from './routes/services.new'
import { Route as ServicesServiceIdEditRouteImport } from './routes/services.$serviceId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationSubmittedRoute = RegistrationSubmittedRouteImport.update({
  id: '/registration-submitted',
  path: '/registration-submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesNewRoute = ServicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesServiceIdEditRoute = ServicesServiceIdEditRouteImport.update({
  id: '/$serviceId/edit',
  path: '/$serviceId/edit',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/earnings': typeof EarningsRoute
  '/notifications': typeof NotificationsRoute
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRoute
  '/registration': typeof RegistrationRoute
  '/registration-submitted': typeof RegistrationSubmittedRoute
  '/services': typeof ServicesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/wallet': typeof WalletRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/services/new': typeof ServicesNewRoute
  '/orders/': typeof OrdersIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/$serviceId/edit': typeof ServicesServiceIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/earnings': typeof EarningsRoute
  '/notifications': typeof NotificationsRoute
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRoute
  '/registration': typeof RegistrationRoute
  '/registration-submitted': typeof RegistrationSubmittedRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/wallet': typeof WalletRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/services/new': typeof ServicesNewRoute
  '/orders': typeof OrdersIndexRoute
  '/services': typeof ServicesIndexRoute
  '/services/$serviceId/edit': typeof ServicesServiceIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/earnings': typeof EarningsRoute
  '/notifications': typeof NotificationsRoute
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRoute
  '/registration': typeof RegistrationRoute
  '/registration-submitted': typeof RegistrationSubmittedRoute
  '/services': typeof ServicesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/wallet': typeof WalletRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/services/new': typeof ServicesNewRoute
  '/orders/': typeof OrdersIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/$serviceId/edit': typeof ServicesServiceIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/earnings'
    | '/notifications'
    | '/otp'
    | '/profile'
    | '/registration'
    | '/registration-submitted'
    | '/services'
    | '/settings'
    | '/shop'
    | '/wallet'
    | '/orders/$orderId'
    | '/services/new'
    | '/orders/'
    | '/services/'
    | '/services/$serviceId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/earnings'
    | '/notifications'
    | '/otp'
    | '/profile'
    | '/registration'
    | '/registration-submitted'
    | '/settings'
    | '/shop'
    | '/wallet'
    | '/orders/$orderId'
    | '/services/new'
    | '/orders'
    | '/services'
    | '/services/$serviceId/edit'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/earnings'
    | '/notifications'
    | '/otp'
    | '/profile'
    | '/registration'
    | '/registration-submitted'
    | '/services'
    | '/settings'
    | '/shop'
    | '/wallet'
    | '/orders/$orderId'
    | '/services/new'
    | '/orders/'
    | '/services/'
    | '/services/$serviceId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  EarningsRoute: typeof EarningsRoute
  NotificationsRoute: typeof NotificationsRoute
  OtpRoute: typeof OtpRoute
  ProfileRoute: typeof ProfileRoute
  RegistrationRoute: typeof RegistrationRoute
  RegistrationSubmittedRoute: typeof RegistrationSubmittedRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  WalletRoute: typeof WalletRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration-submitted': {
      id: '/registration-submitted'
      path: '/registration-submitted'
      fullPath: '/registration-submitted'
      preLoaderRoute: typeof RegistrationSubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/new': {
      id: '/services/new'
      path: '/new'
      fullPath: '/services/new'
      preLoaderRoute: typeof ServicesNewRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$serviceId/edit': {
      id: '/services/$serviceId/edit'
      path: '/$serviceId/edit'
      fullPath: '/services/$serviceId/edit'
      preLoaderRoute: typeof ServicesServiceIdEditRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesNewRoute: typeof ServicesNewRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServicesServiceIdEditRoute: typeof ServicesServiceIdEditRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesNewRoute: ServicesNewRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ServicesServiceIdEditRoute: ServicesServiceIdEditRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  EarningsRoute: EarningsRoute,
  NotificationsRoute: NotificationsRoute,
  OtpRoute: OtpRoute,
  ProfileRoute: ProfileRoute,
  RegistrationRoute: RegistrationRoute,
  RegistrationSubmittedRoute: RegistrationSubmittedRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  WalletRoute: WalletRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
