/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as RegistrationSubmittedRouteImport } from './routes/registration-submitted'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics.index'
import { Route as AnalyticsAchievementsRouteImport } from './routes/analytics.achievements'
import { Route as AnalyticsInsightsRouteImport } from './routes/analytics.insights'
import { Route as AnalyticsLeaderboardRouteImport } from './routes/analytics.leaderboard'
import { Route as DeliveriesIndexRouteImport } from './routes/deliveries.index'
import { Route as DeliveriesDeliveryIdRouteImport } from './routes/deliveries.$deliveryId'
import { Route as HistoryIndexRouteImport } from './routes/history.index'
import { Route as HistoryDeliveryIdRouteImport } from './routes/history.$deliveryId'
import { Route as LiveNavigationDeliveryIdRouteImport } from './routes/live-navigation.$deliveryId'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as MessagesThreadIdRouteImport } from './routes/messages.$threadId'
import { Route as NavigateOrderIdRouteImport } from './routes/navigate.$orderId'
import { Route as NotificationsIndexRouteImport } from './routes/notifications.index'
import { Route as NotificationsAnnouncementsRouteImport } from './routes/notifications.announcements'
import { Route as NotificationsSettingsRouteImport } from './routes/notifications.settings'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as SettingsAboutRouteImport } from './routes/settings.about'
import { Route as SettingsDocumentsRouteImport } from './routes/settings.documents'
import { Route as SettingsLegalRouteImport } from './routes/settings.legal'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsThemeRouteImport } from './routes/settings.theme'
import { Route as SettingsWorkRouteImport } from './routes/settings.work'
import { Route as WalletIndexRouteImport } from './routes/wallet.index'
import { Route as WalletBankRouteImport } from './routes/wallet.bank'
import { Route as WalletEarningsRouteImport } from './routes/wallet.earnings'
import { Route as WalletIncentivesRouteImport } from './routes/wallet.incentives'
import { Route as WalletTransactionsRouteImport } from './routes/wallet.transactions'
import { Route as WalletWithdrawRouteImport } from './routes/wallet.withdraw'
import { Route as SettingsAccountIndexRouteImport } from './routes/settings.account.index'
import { Route as SettingsAccountEditRouteImport } from './routes/settings.account.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationSubmittedRoute = RegistrationSubmittedRouteImport.update({
  id: '/registration-submitted',
  path: '/registration-submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsAchievementsRoute = AnalyticsAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsInsightsRoute = AnalyticsInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsLeaderboardRoute = AnalyticsLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AnalyticsRoute,
} as any)
const DeliveriesIndexRoute = DeliveriesIndexRouteImport.update({
  id: '/deliveries/',
  path: '/deliveries/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesDeliveryIdRoute = DeliveriesDeliveryIdRouteImport.update({
  id: '/deliveries/$deliveryId',
  path: '/deliveries/$deliveryId',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HistoryRoute,
} as any)
const HistoryDeliveryIdRoute = HistoryDeliveryIdRouteImport.update({
  id: '/$deliveryId',
  path: '/$deliveryId',
  getParentRoute: () => HistoryRoute,
} as any)
const LiveNavigationDeliveryIdRoute =
  LiveNavigationDeliveryIdRouteImport.update({
    id: '/live-navigation/$deliveryId',
    path: '/live-navigation/$deliveryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MessagesRoute,
} as any)
const MessagesThreadIdRoute = MessagesThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => MessagesRoute,
} as any)
const NavigateOrderIdRoute = NavigateOrderIdRouteImport.update({
  id: '/navigate/$orderId',
  path: '/navigate/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotificationsRoute,
} as any)
const NotificationsAnnouncementsRoute =
  NotificationsAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => NotificationsRoute,
  } as any)
const NotificationsSettingsRoute = NotificationsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => NotificationsRoute,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDocumentsRoute = SettingsDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLegalRoute = SettingsLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsThemeRoute = SettingsThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsWorkRoute = SettingsWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => SettingsRoute,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WalletRoute,
} as any)
const WalletBankRoute = WalletBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => WalletRoute,
} as any)
const WalletEarningsRoute = WalletEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => WalletRoute,
} as any)
const WalletIncentivesRoute = WalletIncentivesRouteImport.update({
  id: '/incentives',
  path: '/incentives',
  getParentRoute: () => WalletRoute,
} as any)
const WalletTransactionsRoute = WalletTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => WalletRoute,
} as any)
const WalletWithdrawRoute = WalletWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => WalletRoute,
} as any)
const SettingsAccountIndexRoute = SettingsAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountEditRoute = SettingsAccountEditRouteImport.update({
  id: '/account/edit',
  path: '/account/edit',
  getParentRoute: () => SettingsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRouteWithChildren
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRouteWithChildren
  '/otp': typeof OtpRoute
  '/performance': typeof PerformanceRoute
  '/profile': typeof ProfileRoute
  '/registration': typeof RegistrationRoute
  '/registration-submitted': typeof RegistrationSubmittedRoute
  '/settings': typeof SettingsRouteWithChildren
  '/wallet': typeof WalletRouteWithChildren
  '/analytics/achievements': typeof AnalyticsAchievementsRoute
  '/analytics/insights': typeof AnalyticsInsightsRoute
  '/analytics/leaderboard': typeof AnalyticsLeaderboardRoute
  '/deliveries/$deliveryId': typeof DeliveriesDeliveryIdRoute
  '/history/$deliveryId': typeof HistoryDeliveryIdRoute
  '/live-navigation/$deliveryId': typeof LiveNavigationDeliveryIdRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/navigate/$orderId': typeof NavigateOrderIdRoute
  '/notifications/announcements': typeof NotificationsAnnouncementsRoute
  '/notifications/settings': typeof NotificationsSettingsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/documents': typeof SettingsDocumentsRoute
  '/settings/legal': typeof SettingsLegalRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/settings/work': typeof SettingsWorkRoute
  '/wallet/bank': typeof WalletBankRoute
  '/wallet/earnings': typeof WalletEarningsRoute
  '/wallet/incentives': typeof WalletIncentivesRoute
  '/wallet/transactions': typeof WalletTransactionsRoute
  '/wallet/withdraw': typeof WalletWithdrawRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/deliveries/': typeof DeliveriesIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/settings/account/edit': typeof SettingsAccountEditRoute
  '/settings/account/': typeof SettingsAccountIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/otp': typeof OtpRoute
  '/performance': typeof PerformanceRoute
  '/profile': typeof ProfileRoute
  '/registration': typeof RegistrationRoute
  '/registration-submitted': typeof RegistrationSubmittedRoute
  '/analytics/achievements': typeof AnalyticsAchievementsRoute
  '/analytics/insights': typeof AnalyticsInsightsRoute
  '/analytics/leaderboard': typeof AnalyticsLeaderboardRoute
  '/deliveries/$deliveryId': typeof DeliveriesDeliveryIdRoute
  '/history/$deliveryId': typeof HistoryDeliveryIdRoute
  '/live-navigation/$deliveryId': typeof LiveNavigationDeliveryIdRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/navigate/$orderId': typeof NavigateOrderIdRoute
  '/notifications/announcements': typeof NotificationsAnnouncementsRoute
  '/notifications/settings': typeof NotificationsSettingsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/documents': typeof SettingsDocumentsRoute
  '/settings/legal': typeof SettingsLegalRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/settings/work': typeof SettingsWorkRoute
  '/wallet/bank': typeof WalletBankRoute
  '/wallet/earnings': typeof WalletEarningsRoute
  '/wallet/incentives': typeof WalletIncentivesRoute
  '/wallet/transactions': typeof WalletTransactionsRoute
  '/wallet/withdraw': typeof WalletWithdrawRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/deliveries': typeof DeliveriesIndexRoute
  '/history': typeof HistoryIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/wallet': typeof WalletIndexRoute
  '/settings/account/edit': typeof SettingsAccountEditRoute
  '/settings/account': typeof SettingsAccountIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/history': typeof HistoryRouteWithChildren
  '/messages': typeof MessagesRouteWithChildren
  '/notifications': typeof NotificationsRouteWithChildren
  '/otp': typeof OtpRoute
  '/performance': typeof PerformanceRoute
  '/profile': typeof ProfileRoute
  '/registration': typeof RegistrationRoute
  '/registration-submitted': typeof RegistrationSubmittedRoute
  '/settings': typeof SettingsRouteWithChildren
  '/wallet': typeof WalletRouteWithChildren
  '/analytics/achievements': typeof AnalyticsAchievementsRoute
  '/analytics/insights': typeof AnalyticsInsightsRoute
  '/analytics/leaderboard': typeof AnalyticsLeaderboardRoute
  '/deliveries/$deliveryId': typeof DeliveriesDeliveryIdRoute
  '/history/$deliveryId': typeof HistoryDeliveryIdRoute
  '/live-navigation/$deliveryId': typeof LiveNavigationDeliveryIdRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/navigate/$orderId': typeof NavigateOrderIdRoute
  '/notifications/announcements': typeof NotificationsAnnouncementsRoute
  '/notifications/settings': typeof NotificationsSettingsRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/documents': typeof SettingsDocumentsRoute
  '/settings/legal': typeof SettingsLegalRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/theme': typeof SettingsThemeRoute
  '/settings/work': typeof SettingsWorkRoute
  '/wallet/bank': typeof WalletBankRoute
  '/wallet/earnings': typeof WalletEarningsRoute
  '/wallet/incentives': typeof WalletIncentivesRoute
  '/wallet/transactions': typeof WalletTransactionsRoute
  '/wallet/withdraw': typeof WalletWithdrawRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/deliveries/': typeof DeliveriesIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/settings/account/edit': typeof SettingsAccountEditRoute
  '/settings/account/': typeof SettingsAccountIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/messages'
    | '/notifications'
    | '/otp'
    | '/performance'
    | '/profile'
    | '/registration'
    | '/registration-submitted'
    | '/settings'
    | '/wallet'
    | '/analytics/achievements'
    | '/analytics/insights'
    | '/analytics/leaderboard'
    | '/deliveries/$deliveryId'
    | '/history/$deliveryId'
    | '/live-navigation/$deliveryId'
    | '/messages/$threadId'
    | '/navigate/$orderId'
    | '/notifications/announcements'
    | '/notifications/settings'
    | '/orders/$orderId'
    | '/settings/about'
    | '/settings/documents'
    | '/settings/legal'
    | '/settings/notifications'
    | '/settings/security'
    | '/settings/theme'
    | '/settings/work'
    | '/wallet/bank'
    | '/wallet/earnings'
    | '/wallet/incentives'
    | '/wallet/transactions'
    | '/wallet/withdraw'
    | '/analytics/'
    | '/deliveries/'
    | '/history/'
    | '/messages/'
    | '/notifications/'
    | '/orders/'
    | '/settings/'
    | '/wallet/'
    | '/settings/account/edit'
    | '/settings/account/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/otp'
    | '/performance'
    | '/profile'
    | '/registration'
    | '/registration-submitted'
    | '/analytics/achievements'
    | '/analytics/insights'
    | '/analytics/leaderboard'
    | '/deliveries/$deliveryId'
    | '/history/$deliveryId'
    | '/live-navigation/$deliveryId'
    | '/messages/$threadId'
    | '/navigate/$orderId'
    | '/notifications/announcements'
    | '/notifications/settings'
    | '/orders/$orderId'
    | '/settings/about'
    | '/settings/documents'
    | '/settings/legal'
    | '/settings/notifications'
    | '/settings/security'
    | '/settings/theme'
    | '/settings/work'
    | '/wallet/bank'
    | '/wallet/earnings'
    | '/wallet/incentives'
    | '/wallet/transactions'
    | '/wallet/withdraw'
    | '/analytics'
    | '/deliveries'
    | '/history'
    | '/messages'
    | '/notifications'
    | '/orders'
    | '/settings'
    | '/wallet'
    | '/settings/account/edit'
    | '/settings/account'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auth'
    | '/dashboard'
    | '/history'
    | '/messages'
    | '/notifications'
    | '/otp'
    | '/performance'
    | '/profile'
    | '/registration'
    | '/registration-submitted'
    | '/settings'
    | '/wallet'
    | '/analytics/achievements'
    | '/analytics/insights'
    | '/analytics/leaderboard'
    | '/deliveries/$deliveryId'
    | '/history/$deliveryId'
    | '/live-navigation/$deliveryId'
    | '/messages/$threadId'
    | '/navigate/$orderId'
    | '/notifications/announcements'
    | '/notifications/settings'
    | '/orders/$orderId'
    | '/settings/about'
    | '/settings/documents'
    | '/settings/legal'
    | '/settings/notifications'
    | '/settings/security'
    | '/settings/theme'
    | '/settings/work'
    | '/wallet/bank'
    | '/wallet/earnings'
    | '/wallet/incentives'
    | '/wallet/transactions'
    | '/wallet/withdraw'
    | '/analytics/'
    | '/deliveries/'
    | '/history/'
    | '/messages/'
    | '/notifications/'
    | '/orders/'
    | '/settings/'
    | '/wallet/'
    | '/settings/account/edit'
    | '/settings/account/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  MessagesRoute: typeof MessagesRouteWithChildren
  NotificationsRoute: typeof NotificationsRouteWithChildren
  OtpRoute: typeof OtpRoute
  PerformanceRoute: typeof PerformanceRoute
  ProfileRoute: typeof ProfileRoute
  RegistrationRoute: typeof RegistrationRoute
  RegistrationSubmittedRoute: typeof RegistrationSubmittedRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  WalletRoute: typeof WalletRouteWithChildren
  DeliveriesDeliveryIdRoute: typeof DeliveriesDeliveryIdRoute
  LiveNavigationDeliveryIdRoute: typeof LiveNavigationDeliveryIdRoute
  NavigateOrderIdRoute: typeof NavigateOrderIdRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  DeliveriesIndexRoute: typeof DeliveriesIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration-submitted': {
      id: '/registration-submitted'
      path: '/registration-submitted'
      fullPath: '/registration-submitted'
      preLoaderRoute: typeof RegistrationSubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/achievements': {
      id: '/analytics/achievements'
      path: '/achievements'
      fullPath: '/analytics/achievements'
      preLoaderRoute: typeof AnalyticsAchievementsRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/insights': {
      id: '/analytics/insights'
      path: '/insights'
      fullPath: '/analytics/insights'
      preLoaderRoute: typeof AnalyticsInsightsRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/leaderboard': {
      id: '/analytics/leaderboard'
      path: '/leaderboard'
      fullPath: '/analytics/leaderboard'
      preLoaderRoute: typeof AnalyticsLeaderboardRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/deliveries/': {
      id: '/deliveries/'
      path: '/deliveries'
      fullPath: '/deliveries/'
      preLoaderRoute: typeof DeliveriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries/$deliveryId': {
      id: '/deliveries/$deliveryId'
      path: '/deliveries/$deliveryId'
      fullPath: '/deliveries/$deliveryId'
      preLoaderRoute: typeof DeliveriesDeliveryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/history/$deliveryId': {
      id: '/history/$deliveryId'
      path: '/$deliveryId'
      fullPath: '/history/$deliveryId'
      preLoaderRoute: typeof HistoryDeliveryIdRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/live-navigation/$deliveryId': {
      id: '/live-navigation/$deliveryId'
      path: '/live-navigation/$deliveryId'
      fullPath: '/live-navigation/$deliveryId'
      preLoaderRoute: typeof LiveNavigationDeliveryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/messages/$threadId': {
      id: '/messages/$threadId'
      path: '/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof MessagesThreadIdRouteImport
      parentRoute: typeof MessagesRoute
    }
    '/navigate/$orderId': {
      id: '/navigate/$orderId'
      path: '/navigate/$orderId'
      fullPath: '/navigate/$orderId'
      preLoaderRoute: typeof NavigateOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof NotificationsRoute
    }
    '/notifications/announcements': {
      id: '/notifications/announcements'
      path: '/announcements'
      fullPath: '/notifications/announcements'
      preLoaderRoute: typeof NotificationsAnnouncementsRouteImport
      parentRoute: typeof NotificationsRoute
    }
    '/notifications/settings': {
      id: '/notifications/settings'
      path: '/settings'
      fullPath: '/notifications/settings'
      preLoaderRoute: typeof NotificationsSettingsRouteImport
      parentRoute: typeof NotificationsRoute
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/documents': {
      id: '/settings/documents'
      path: '/documents'
      fullPath: '/settings/documents'
      preLoaderRoute: typeof SettingsDocumentsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/legal': {
      id: '/settings/legal'
      path: '/legal'
      fullPath: '/settings/legal'
      preLoaderRoute: typeof SettingsLegalRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/theme': {
      id: '/settings/theme'
      path: '/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof SettingsThemeRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/work': {
      id: '/settings/work'
      path: '/work'
      fullPath: '/settings/work'
      preLoaderRoute: typeof SettingsWorkRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/bank': {
      id: '/wallet/bank'
      path: '/bank'
      fullPath: '/wallet/bank'
      preLoaderRoute: typeof WalletBankRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/earnings': {
      id: '/wallet/earnings'
      path: '/earnings'
      fullPath: '/wallet/earnings'
      preLoaderRoute: typeof WalletEarningsRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/incentives': {
      id: '/wallet/incentives'
      path: '/incentives'
      fullPath: '/wallet/incentives'
      preLoaderRoute: typeof WalletIncentivesRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/transactions': {
      id: '/wallet/transactions'
      path: '/transactions'
      fullPath: '/wallet/transactions'
      preLoaderRoute: typeof WalletTransactionsRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/withdraw': {
      id: '/wallet/withdraw'
      path: '/withdraw'
      fullPath: '/wallet/withdraw'
      preLoaderRoute: typeof WalletWithdrawRouteImport
      parentRoute: typeof WalletRoute
    }
    '/settings/account/': {
      id: '/settings/account/'
      path: '/account'
      fullPath: '/settings/account/'
      preLoaderRoute: typeof SettingsAccountIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account/edit': {
      id: '/settings/account/edit'
      path: '/account/edit'
      fullPath: '/settings/account/edit'
      preLoaderRoute: typeof SettingsAccountEditRouteImport
      parentRoute: typeof SettingsRoute
    }
  }
}

interface AnalyticsRouteChildren {
  AnalyticsAchievementsRoute: typeof AnalyticsAchievementsRoute
  AnalyticsInsightsRoute: typeof AnalyticsInsightsRoute
  AnalyticsLeaderboardRoute: typeof AnalyticsLeaderboardRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsAchievementsRoute: AnalyticsAchievementsRoute,
  AnalyticsInsightsRoute: AnalyticsInsightsRoute,
  AnalyticsLeaderboardRoute: AnalyticsLeaderboardRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

interface HistoryRouteChildren {
  HistoryDeliveryIdRoute: typeof HistoryDeliveryIdRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryDeliveryIdRoute: HistoryDeliveryIdRoute,
  HistoryIndexRoute: HistoryIndexRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

interface MessagesRouteChildren {
  MessagesThreadIdRoute: typeof MessagesThreadIdRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

const MessagesRouteChildren: MessagesRouteChildren = {
  MessagesThreadIdRoute: MessagesThreadIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}

const MessagesRouteWithChildren = MessagesRoute._addFileChildren(
  MessagesRouteChildren,
)

interface NotificationsRouteChildren {
  NotificationsAnnouncementsRoute: typeof NotificationsAnnouncementsRoute
  NotificationsSettingsRoute: typeof NotificationsSettingsRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
}

const NotificationsRouteChildren: NotificationsRouteChildren = {
  NotificationsAnnouncementsRoute: NotificationsAnnouncementsRoute,
  NotificationsSettingsRoute: NotificationsSettingsRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
}

const NotificationsRouteWithChildren = NotificationsRoute._addFileChildren(
  NotificationsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsDocumentsRoute: typeof SettingsDocumentsRoute
  SettingsLegalRoute: typeof SettingsLegalRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsThemeRoute: typeof SettingsThemeRoute
  SettingsWorkRoute: typeof SettingsWorkRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsAccountEditRoute: typeof SettingsAccountEditRoute
  SettingsAccountIndexRoute: typeof SettingsAccountIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsDocumentsRoute: SettingsDocumentsRoute,
  SettingsLegalRoute: SettingsLegalRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsThemeRoute: SettingsThemeRoute,
  SettingsWorkRoute: SettingsWorkRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsAccountEditRoute: SettingsAccountEditRoute,
  SettingsAccountIndexRoute: SettingsAccountIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface WalletRouteChildren {
  WalletBankRoute: typeof WalletBankRoute
  WalletEarningsRoute: typeof WalletEarningsRoute
  WalletIncentivesRoute: typeof WalletIncentivesRoute
  WalletTransactionsRoute: typeof WalletTransactionsRoute
  WalletWithdrawRoute: typeof WalletWithdrawRoute
  WalletIndexRoute: typeof WalletIndexRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletBankRoute: WalletBankRoute,
  WalletEarningsRoute: WalletEarningsRoute,
  WalletIncentivesRoute: WalletIncentivesRoute,
  WalletTransactionsRoute: WalletTransactionsRoute,
  WalletWithdrawRoute: WalletWithdrawRoute,
  WalletIndexRoute: WalletIndexRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  HistoryRoute: HistoryRouteWithChildren,
  MessagesRoute: MessagesRouteWithChildren,
  NotificationsRoute: NotificationsRouteWithChildren,
  OtpRoute: OtpRoute,
  PerformanceRoute: PerformanceRoute,
  ProfileRoute: ProfileRoute,
  RegistrationRoute: RegistrationRoute,
  RegistrationSubmittedRoute: RegistrationSubmittedRoute,
  SettingsRoute: SettingsRouteWithChildren,
  WalletRoute: WalletRouteWithChildren,
  DeliveriesDeliveryIdRoute: DeliveriesDeliveryIdRoute,
  LiveNavigationDeliveryIdRoute: LiveNavigationDeliveryIdRoute,
  NavigateOrderIdRoute: NavigateOrderIdRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  DeliveriesIndexRoute: DeliveriesIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
