/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EarningsRouteImport } from './routes/earnings'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as RegistrationSubmittedRouteImport } from './routes/registration-submitted'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as MessagesThreadIdRouteImport } from './routes/messages.$threadId'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesNewRouteImport } from './routes/services.new'
import { Route as WalletIndexRouteImport } from './routes/wallet.index'
import { Route as WalletWithdrawRouteImport } from './routes/wallet.withdraw'
import { Route as ServicesServiceIdEditRouteImport } from './routes/services.$serviceId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EarningsRoute = EarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationSubmittedRoute = RegistrationSubmittedRouteImport.update({
  id: '/registration-submitted',
  path: '/registration-submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesThreadIdRoute = MessagesThreadIdRouteImport.update({
  id: '/messages/$threadId',
  path: '/messages/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesNewRoute = ServicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ServicesRoute,
} as any)
const WalletIndexRoute = WalletIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WalletRoute,
} as any)
const WalletWithdrawRoute = WalletWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => WalletRoute,
} as any)
const ServicesServiceIdEditRoute = ServicesServiceIdEditRouteImport.update({
  id: '/$serviceId/edit',
  path: '/$serviceId/edit',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/earnings': typeof EarningsRoute
  '/notifications': typeof NotificationsRoute
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRoute
  '/registration': typeof RegistrationRoute
  '/registration-submitted': typeof RegistrationSubmittedRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/wallet': typeof WalletRouteWithChildren
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/services/new': typeof ServicesNewRoute
  '/wallet/withdraw': typeof WalletWithdrawRoute
  '/customers/': typeof CustomersIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/services/$serviceId/edit': typeof ServicesServiceIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/earnings': typeof EarningsRoute
  '/notifications': typeof NotificationsRoute
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRoute
  '/registration': typeof RegistrationRoute
  '/registration-submitted': typeof RegistrationSubmittedRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/services/new': typeof ServicesNewRoute
  '/wallet/withdraw': typeof WalletWithdrawRoute
  '/customers': typeof CustomersIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/services': typeof ServicesIndexRoute
  '/wallet': typeof WalletIndexRoute
  '/services/$serviceId/edit': typeof ServicesServiceIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/earnings': typeof EarningsRoute
  '/notifications': typeof NotificationsRoute
  '/otp': typeof OtpRoute
  '/profile': typeof ProfileRoute
  '/registration': typeof RegistrationRoute
  '/registration-submitted': typeof RegistrationSubmittedRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/wallet': typeof WalletRouteWithChildren
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/messages/$threadId': typeof MessagesThreadIdRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/services/new': typeof ServicesNewRoute
  '/wallet/withdraw': typeof WalletWithdrawRoute
  '/customers/': typeof CustomersIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/wallet/': typeof WalletIndexRoute
  '/services/$serviceId/edit': typeof ServicesServiceIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/announcements'
    | '/auth'
    | '/dashboard'
    | '/earnings'
    | '/notifications'
    | '/otp'
    | '/profile'
    | '/registration'
    | '/registration-submitted'
    | '/reviews'
    | '/services'
    | '/settings'
    | '/shop'
    | '/wallet'
    | '/customers/$customerId'
    | '/messages/$threadId'
    | '/orders/$orderId'
    | '/services/new'
    | '/wallet/withdraw'
    | '/customers/'
    | '/messages/'
    | '/orders/'
    | '/services/'
    | '/wallet/'
    | '/services/$serviceId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/announcements'
    | '/auth'
    | '/dashboard'
    | '/earnings'
    | '/notifications'
    | '/otp'
    | '/profile'
    | '/registration'
    | '/registration-submitted'
    | '/reviews'
    | '/settings'
    | '/shop'
    | '/customers/$customerId'
    | '/messages/$threadId'
    | '/orders/$orderId'
    | '/services/new'
    | '/wallet/withdraw'
    | '/customers'
    | '/messages'
    | '/orders'
    | '/services'
    | '/wallet'
    | '/services/$serviceId/edit'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/announcements'
    | '/auth'
    | '/dashboard'
    | '/earnings'
    | '/notifications'
    | '/otp'
    | '/profile'
    | '/registration'
    | '/registration-submitted'
    | '/reviews'
    | '/services'
    | '/settings'
    | '/shop'
    | '/wallet'
    | '/customers/$customerId'
    | '/messages/$threadId'
    | '/orders/$orderId'
    | '/services/new'
    | '/wallet/withdraw'
    | '/customers/'
    | '/messages/'
    | '/orders/'
    | '/services/'
    | '/wallet/'
    | '/services/$serviceId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  EarningsRoute: typeof EarningsRoute
  NotificationsRoute: typeof NotificationsRoute
  OtpRoute: typeof OtpRoute
  ProfileRoute: typeof ProfileRoute
  RegistrationRoute: typeof RegistrationRoute
  RegistrationSubmittedRoute: typeof RegistrationSubmittedRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  WalletRoute: typeof WalletRouteWithChildren
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  MessagesThreadIdRoute: typeof MessagesThreadIdRoute
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/earnings': {
      id: '/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof EarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration-submitted': {
      id: '/registration-submitted'
      path: '/registration-submitted'
      fullPath: '/registration-submitted'
      preLoaderRoute: typeof RegistrationSubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$threadId': {
      id: '/messages/$threadId'
      path: '/messages/$threadId'
      fullPath: '/messages/$threadId'
      preLoaderRoute: typeof MessagesThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/new': {
      id: '/services/new'
      path: '/new'
      fullPath: '/services/new'
      preLoaderRoute: typeof ServicesNewRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/wallet/': {
      id: '/wallet/'
      path: '/'
      fullPath: '/wallet/'
      preLoaderRoute: typeof WalletIndexRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/withdraw': {
      id: '/wallet/withdraw'
      path: '/withdraw'
      fullPath: '/wallet/withdraw'
      preLoaderRoute: typeof WalletWithdrawRouteImport
      parentRoute: typeof WalletRoute
    }
    '/services/$serviceId/edit': {
      id: '/services/$serviceId/edit'
      path: '/$serviceId/edit'
      fullPath: '/services/$serviceId/edit'
      preLoaderRoute: typeof ServicesServiceIdEditRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesNewRoute: typeof ServicesNewRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  ServicesServiceIdEditRoute: typeof ServicesServiceIdEditRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesNewRoute: ServicesNewRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  ServicesServiceIdEditRoute: ServicesServiceIdEditRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface WalletRouteChildren {
  WalletWithdrawRoute: typeof WalletWithdrawRoute
  WalletIndexRoute: typeof WalletIndexRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletWithdrawRoute: WalletWithdrawRoute,
  WalletIndexRoute: WalletIndexRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  EarningsRoute: EarningsRoute,
  NotificationsRoute: NotificationsRoute,
  OtpRoute: OtpRoute,
  ProfileRoute: ProfileRoute,
  RegistrationRoute: RegistrationRoute,
  RegistrationSubmittedRoute: RegistrationSubmittedRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  WalletRoute: WalletRouteWithChildren,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  MessagesThreadIdRoute: MessagesThreadIdRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
